# 자연어 생성

In [3]:
path = "C:\\Users\\Windows\\Desktop\\대학교\\4학년 여름방학\\Big_AI\\자연어처리\\pytest\\data\\eng-kor\\"

In [4]:
import pandas as pd

data = pd.read_csv(path+"eng-kor_small.txt", names=["source", "target"], sep = "\t", encoding = "utf-8")
print("data length : \n", len(data))
print("data type : \n", type(data))
print("data shape : \n", data.shape)
print("data sample : \n", data.sample(5))

print("data.target length : \n", len(data.target))
print("data.target type : \n", type(data.target))
print("data.target shape : \n", data.target.shape)
print("data.target sample : \n", data.target.sample(5))

data length : 
 1000
data type : 
 <class 'pandas.core.frame.DataFrame'>
data shape : 
 (1000, 2)
data sample : 
                   source         target
906  Drink to my health.     건강을 위해 건배.
75             How cute!          귀엽잖아!
836   I sent Tom a text.  난 톰한테 문자 보냈어.
802   Champagne, please.       샴폐인 부탁해.
110            What fun!          재밌잖아!
data.target length : 
 1000
data.target type : 
 <class 'pandas.core.series.Series'>
data.target shape : 
 (1000,)
data.target sample : 
 45             저리 가.
598         담배 냄새 나.
847    톰이 먹는 걸 지켜봤어.
168             고마워.
190           누가 알아?
Name: target, dtype: object


## 시작부호와 종료부호 부착

In [5]:
data.target_input = data.target.apply(lambda x : '\t' + x + '\n')
data.target_target = data.target.apply(lambda x : x + "\n")
print("\ndata.target_input : \n", data.target_input)
print("\ndata.target_target : \n", data.target_target)

print("data.target_input length : \n", len(data.target_input))
print("data.target_input type : \n", type(data.target_input))
print("data.target_input shape : \n", data.target_input.shape)
print("data.target_input sample : \n", data.target_input.sample(5))


data.target_input : 
 0                 \t가.\n
1                \t안녕.\n
2                \t뛰어!\n
3                \t뛰어.\n
4                \t누구?\n
             ...        
995     \t노래하는 거 좋아해요?\n
996      \t노래하는 거 좋아해?\n
997    \t고양이를 좋아하지 않아?\n
998      \t꿈은 이루어질 거야.\n
999     \t모두 그녀를 사랑한다.\n
Name: target, Length: 1000, dtype: object

data.target_target : 
 0                 가.\n
1                안녕.\n
2                뛰어!\n
3                뛰어.\n
4                누구?\n
            ...       
995     노래하는 거 좋아해요?\n
996      노래하는 거 좋아해?\n
997    고양이를 좋아하지 않아?\n
998      꿈은 이루어질 거야.\n
999     모두 그녀를 사랑한다.\n
Name: target, Length: 1000, dtype: object
data.target_input length : 
 1000
data.target_input type : 
 <class 'pandas.core.series.Series'>
data.target_input shape : 
 (1000,)
data.target_input sample : 
 298             \t다시 확인해.\n
216            \t톰은 잊어버려.\n
897    \t너는 내 것을 가질 수 있다.\n
612           \t톰은 정말 멋져.\n
410             \t나는 몰라요.\n
Name: target, dtype: object


<ipython-input-5-953c8a28e506>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.target_input = data.target.apply(lambda x : '\t' + x + '\n')
<ipython-input-5-953c8a28e506>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.target_target = data.target.apply(lambda x : x + "\n")


## 문장의 길이 maxlen 설정하기

In [6]:
# source 문장의 최대 길이
max_src_len = data.source.apply(lambda x : len(x)).max()
print("source sentence max length : ", max_src_len)

# target_input 문장의 최대 길이
max_tar_len = data.target_input.apply(lambda x : len(x)).max() - 2 # "\t"와 "\n"의 길이는 제외
print("target sentence max length : ", max_tar_len)

source sentence max length :  20
target sentence max length :  19


## 데이터 Tokenizing

In [7]:
# source 언어 Tokenizing

from keras.preprocessing.text import Tokenizer

tokenizer_source = Tokenizer(num_words=None, char_level=True, lower = False) # 음절 기반, 문장부호를 제거하진 않음
tokenizer_source.fit_on_texts(data.source)
word_index_source = tokenizer_source.word_index

print("전체에서 %s개의 고유한 토큰을 찾았습니다." % len(word_index_source))
print("word_index_source : ", word_index_source)

전체에서 64개의 고유한 토큰을 찾았습니다.
word_index_source :  {' ': 1, 'e': 2, 'o': 3, '.': 4, 'a': 5, 't': 6, 'i': 7, 's': 8, 'n': 9, 'r': 10, 'l': 11, 'd': 12, 'm': 13, 'h': 14, 'y': 15, 'u': 16, 'T': 17, 'g': 18, 'I': 19, 'c': 20, 'p': 21, 'w': 22, 'k': 23, "'": 24, 'v': 25, 'b': 26, 'f': 27, '?': 28, 'S': 29, '!': 30, 'W': 31, 'H': 32, 'C': 33, 'D': 34, 'E': 35, 'K': 36, 'A': 37, 'G': 38, 'Y': 39, 'N': 40, 'x': 41, 'F': 42, 'B': 43, 'L': 44, 'M': 45, 'q': 46, ',': 47, 'P': 48, 'R': 49, 'O': 50, 'z': 51, 'J': 52, 'j': 53, 'Q': 54, '-': 55, '7': 56, ':': 57, '4': 58, '5': 59, 'U': 60, '2': 61, '0': 62, '1': 63, '3': 64}


In [8]:
# target 언어 Tokenizing
tokenizer_target = Tokenizer(num_words=None, char_level=True, lower = False) # 음절 기반, 문장부호를 제거하진 않음
tokenizer_target.fit_on_texts(data.target_input)
word_index_target = tokenizer_target.word_index

print("전체에서 %s개의 고유한 토큰을 찾았습니다." % len(word_index_target))
print("word_index_target : ", word_index_target)

전체에서 558개의 고유한 토큰을 찾았습니다.
word_index_target :  {' ': 1, '\t': 2, '\n': 3, '.': 4, '어': 5, '이': 6, '톰': 7, '해': 8, '아': 9, '은': 10, '다': 11, '그': 12, '가': 13, '는': 14, '?': 15, '나': 16, '거': 17, '!': 18, '고': 19, '하': 20, '을': 21, '했': 22, '요': 23, '있': 24, '야': 25, '지': 26, '었': 27, '사': 28, '난': 29, '말': 30, '들': 31, '기': 32, '게': 33, '리': 34, '를': 35, '니': 36, '도': 37, '우': 38, '좋': 39, '와': 40, '내': 41, '에': 42, '람': 43, '무': 44, '자': 45, '마': 46, '서': 47, '봐': 48, '한': 49, '계': 50, '안': 51, '네': 52, '시': 53, '속': 54, '너': 55, '수': 56, '모': 57, '만': 58, '짓': 59, '라': 60, '두': 61, '누': 62, '일': 63, '세': 64, '정': 65, '웃': 66, '로': 67, '않': 68, '줘': 69, '았': 70, '제': 71, '렸': 72, '걸': 73, '없': 74, '려': 75, '물': 76, '미': 77, '저': 78, '여': 79, '건': 80, '죽': 81, '으': 82, '워': 83, '조': 84, '주': 85, '린': 86, '신': 87, '것': 88, '의': 89, '져': 90, '심': 91, '좀': 92, '운': 93, '인': 94, '구': 95, '진': 96, '렇': 97, '날': 98, '입': 99, '래': 100, '울': 101, '전': 102, '빨': 103, '피': 104, '히': 105, '할': 106

## 데이터 Sequencing

In [9]:
encoder_input = tokenizer_source.texts_to_sequences(data.source)

print("Result of encoder_input sequencing : ")
print(data.source[0], encoder_input[0])
print(data.source[1], encoder_input[1])
print(data.source[2], encoder_input[2])
print(data.source[3], encoder_input[3])

Result of encoder_input sequencing : 
Go. [38, 3, 4]
Hi. [32, 7, 4]
Run! [49, 16, 9, 30]
Run. [49, 16, 9, 4]


In [10]:
decoder_input = tokenizer_target.texts_to_sequences(data.target_input)
decoder_target = tokenizer_target.texts_to_sequences(data.target_target)

print('Result of decoder_input sequencing : ')
print(data.target_input[0], decoder_input[0])
print(data.target_input[1], decoder_input[1])
print(data.target_input[2], decoder_input[2])

print('Result of decoder_target sequencing : ')
print(data.target_target[0], decoder_target[0])
print(data.target_target[1], decoder_target[1])
print(data.target_target[2], decoder_target[2])

print('Result of decoder_target sequencing : ')
print(data.target_target[0], decoder_target[0])
print(data.target_target[1], decoder_target[1])
print(data.target_target[2], decoder_target[2])

Result of decoder_input sequencing : 
	가.
 [2, 13, 4, 3]
	안녕.
 [2, 51, 223, 4, 3]
	뛰어!
 [2, 272, 5, 18, 3]
Result of decoder_target sequencing : 
가.
 [13, 4, 3]
안녕.
 [51, 223, 4, 3]
뛰어!
 [272, 5, 18, 3]
Result of decoder_target sequencing : 
가.
 [13, 4, 3]
안녕.
 [51, 223, 4, 3]
뛰어!
 [272, 5, 18, 3]


## 데이터 Padding

In [12]:
from keras_preprocessing.sequence import pad_sequences

encoder_input = pad_sequences(encoder_input, maxlen = max_src_len, padding = "post")
decoder_input = pad_sequences(decoder_input, maxlen = max_tar_len, padding = "post")
decoder_target = pad_sequences(decoder_target, maxlen = max_tar_len, padding = "post")

print("Padding result sample : ")
print(data.target_input[0], decoder_input[0])

print("decoder_input length : ", len(decoder_input))
print("decoder_input type : ", type(decoder_input))
print("decoder_input shape : ", decoder_input.shape)

Padding result sample : 
	가.
 [ 2 13  4  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
decoder_input length :  1000
decoder_input type :  <class 'numpy.ndarray'>
decoder_input shape :  (1000, 19)


In [13]:
from tensorflow.keras.utils import to_categorical

encoder_input = to_categorical(encoder_input, num_classes = len(word_index_source) + 1)
decoder_input = to_categorical(decoder_input, num_classes = len(word_index_target) + 1)
decoder_target = to_categorical(decoder_target, num_classes = len(word_index_target) + 1)

print("Result of One-Hot Encodded decoder_input sequencing : ")
print(decoder_input.shape)
print(data.target_input[0], decoder_input[0])

Result of One-Hot Encodded decoder_input sequencing : 
(1000, 19, 559)
	가.
 [[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [14]:
print("0-0\n", decoder_input[0][0])
print("0-1\n", decoder_input[0][1])
print("0-2\n", decoder_input[0][2])
print("0-3\n", decoder_input[0][3])
print("0-18\n", decoder_input[0][18])

0-0
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [15]:
print("decoder_input length : ", len(decoder_input))
print("decoder_input type : ", type(decoder_input))
print("decoder_input shape : ", decoder_input.shape)

decoder_input length :  1000
decoder_input type :  <class 'numpy.ndarray'>
decoder_input shape :  (1000, 19, 559)


## 훈련용 Encoder

In [16]:
from keras.models import Model
from keras.layers import Input,LSTM, Dense

encoder_inputs = Input(shape = (None, len(word_index_source) + 1))
encoder_lstm = LSTM(256, return_state=True)
_, state_h, state_c = encoder_lstm(encoder_inputs)
encoder_states = [state_h, state_c]

## 훈련용 Decoder

In [17]:
decoder_inputs = Input(shape=(None, len(word_index_target) + 1))
decoder_lstm = LSTM(256, return_sequences = True, return_state = True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state=encoder_states)
decoder_dense = Dense(len(word_index_target) + 1, activation = "softmax")
decoder_outputs = decoder_dense(decoder_outputs)

## 모델 훈련

In [18]:
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
model.compile(optimizer = "rmsprop", loss = "categorical_crossentropy")
model.fit(x=[encoder_input, decoder_input], y = decoder_target, batch_size = 64, epochs = 50, validation_split = 0.2)

Epoch 1/50
13/13 [==============================] - 10s 423ms/step - loss: 3.4260 - val_loss: 3.1424
Epoch 2/50
13/13 [==============================] - 4s 297ms/step - loss: 2.2710 - val_loss: 3.2148
Epoch 3/50
13/13 [==============================] - 4s 318ms/step - loss: 2.2310 - val_loss: 3.2592
Epoch 4/50
13/13 [==============================] - 4s 318ms/step - loss: 2.1923 - val_loss: 2.9773
Epoch 5/50
13/13 [==============================] - 4s 289ms/step - loss: 2.1488 - val_loss: 2.9591
Epoch 6/50
13/13 [==============================] - 4s 306ms/step - loss: 2.1103 - val_loss: 2.9520
Epoch 7/50
13/13 [==============================] - 5s 369ms/step - loss: 2.0740 - val_loss: 2.9217
Epoch 8/50
13/13 [==============================] - 4s 322ms/step - loss: 2.0451 - val_loss: 3.1573
Epoch 9/50
13/13 [==============================] - 4s 298ms/step - loss: 2.0319 - val_loss: 2.9319
Epoch 10/50
13/13 [==============================] - 4s 323ms/step - loss: 1.9797 - val_loss: 2.990

## 예측용 Encoder

In [19]:
encoder_model = Model(inputs = encoder_inputs, outputs = encoder_states)

## 예측용 Decoder

In [20]:
decoder_state_input_h = Input(shape = (256,)) # Encoder vector를 받기 위함
decoder_state_input_c = Input(shape = (256,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = decoder_lstm(decoder_inputs, initial_state = decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)

decoder_model = Model(inputs = [decoder_inputs] + decoder_states_inputs, outputs = [decoder_outputs] + decoder_states) # input으론 target_input과 현재의 문장상태, output으론 예측 결과와 은닉상태와 셀상태가 나오게 한다.

## Word Dictionary 구성

In [21]:
index_to_src = dict((i, char) for char, i in word_index_source.items())
index_to_tar = dict((i, char) for char, i in word_index_target.items())
print(index_to_tar)

{1: ' ', 2: '\t', 3: '\n', 4: '.', 5: '어', 6: '이', 7: '톰', 8: '해', 9: '아', 10: '은', 11: '다', 12: '그', 13: '가', 14: '는', 15: '?', 16: '나', 17: '거', 18: '!', 19: '고', 20: '하', 21: '을', 22: '했', 23: '요', 24: '있', 25: '야', 26: '지', 27: '었', 28: '사', 29: '난', 30: '말', 31: '들', 32: '기', 33: '게', 34: '리', 35: '를', 36: '니', 37: '도', 38: '우', 39: '좋', 40: '와', 41: '내', 42: '에', 43: '람', 44: '무', 45: '자', 46: '마', 47: '서', 48: '봐', 49: '한', 50: '계', 51: '안', 52: '네', 53: '시', 54: '속', 55: '너', 56: '수', 57: '모', 58: '만', 59: '짓', 60: '라', 61: '두', 62: '누', 63: '일', 64: '세', 65: '정', 66: '웃', 67: '로', 68: '않', 69: '줘', 70: '았', 71: '제', 72: '렸', 73: '걸', 74: '없', 75: '려', 76: '물', 77: '미', 78: '저', 79: '여', 80: '건', 81: '죽', 82: '으', 83: '워', 84: '조', 85: '주', 86: '린', 87: '신', 88: '것', 89: '의', 90: '져', 91: '심', 92: '좀', 93: '운', 94: '인', 95: '구', 96: '진', 97: '렇', 98: '날', 99: '입', 100: '래', 101: '울', 102: '전', 103: '빨', 104: '피', 105: '히', 106: '할', 107: '보', 108: '러', 109: '파', 110: '소', 111: 

## 예측함수

In [22]:
def decode_sequence(input_seq):
  states_value = encoder_model.predict(input_seq) # 초기 문장상태벡터를 얻음
  target_seq = np.zeros((1, 1, len(word_index_target) + 1)) # 디코더 초기화
  target_seq[0, 0, word_index_target["\t"]] = 1. # 디코더의 첫 시작은 "\t"이므로 원-핫 인코딩으로 기록
  stop_condition = False
  decoded_sentence = ""

  while not stop_condition:
    output_tokens, h, c = decoder_model.predict([target_seq] + states_value) # target_input과 문장상태벡터 입력
    sampled_token_index = np.argmax(output_tokens)

    if (sampled_token_index == 0):
      sampled_token_index = 1 # 1은 공백 음절

    sampled_char = index_to_tar[sampled_token_index]
    decoded_sentence += sampled_char

    if (sampled_char == "\n" or len(decoded_sentence) > max_tar_len):
      stop_condition = True
    
    target_seq = np.zeros((1, 1, len(word_index_target) + 1))
    target_seq[0, 0, sampled_token_index] = 1.
    states_value = [h, c]

  return decoded_sentence

In [23]:
import numpy as np

for seq_index in [1, 2, 3]:
  input_seq = encoder_input[seq_index:seq_index+1] # 3차원 배열에선 [n:n+1] 형태로 출력해야 3차원이 유지되면서 n번째가 출력된다.
  decoded_sentence = decode_sequence(input_seq)

  print(35 * "-")
  print("입력 문장 : ", data.source[seq_index])
  print("정답 문장 : ", data.target[seq_index][:len(data.target[seq_index])])
  print("번역기가 번역한 문장 : ", decoded_sentence[:len(decoded_sentence) - 1]) # "\n"은 빼고 출력

1/1 [==============================] - 0s 34ms/step
-----------------------------------
입력 문장 :  Hi.
정답 문장 :  안녕.
번역기가 번역한 문장 :  안녕.
1/1 [==============================] - 0s 36ms/step
-----------------------------------
입력 문장 :  Run!
정답 문장 :  뛰어!
번역기가 번역한 문장 :  어.
1/1 [==============================] - 0s 50ms/step
-----------------------------------
입력 문장 :  Run.
정답 문장 :  뛰어.
번역기가 번역한 문장 :  어.


In [24]:
input_seq_1 = tokenizer_source.texts_to_sequences([list("wait")])
input_seq_1 = pad_sequences(input_seq_1, maxlen = max_src_len, padding = "post")
input_seq_1 = to_categorical(input_seq_1, num_classes = len(word_index_source) + 1)

decoded_sentence = decode_sequence(input_seq_1)
print(decoded_sentence)

1/1 [==============================] - 0s 29ms/step
이렇게 귀엽니다니!



# 자연어생성 연습문제

In [42]:
import pandas as pd

data = pd.read_csv("C:\\Users\\Windows\\Desktop\\대학교\\4학년 여름방학\\Big_AI\\자연어처리\\pytest\\data\\kor-eng\\kor-eng.txt", names=["source", "target"], sep = "\t", encoding = "utf-8")
data = data.iloc[:30000]
print("data length : \n", len(data))
print("data type : \n", type(data))
print("data shape : \n", data.shape)
print("data sample : \n", data.sample(5))

print("data.target length : \n", len(data.target))
print("data.target type : \n", type(data.target))
print("data.target shape : \n", data.target.shape)
print("data.target sample : \n", data.target.sample(5))

data length : 
 30000
data type : 
 <class 'pandas.core.frame.DataFrame'>
data shape : 
 (30000, 2)
data sample : 
                                source  \
14390          뭐 그렇다한들 이 잘생김이 어딜 가겠어?   
3196               나는 교육 제도가 바뀌기를 바래.   
19736             빠른 시일내에 정리하여 보내겠어요.   
13028           검사를 위하여 나는 부산에 가야 해요.   
19945  죄송한 말씀이지만 다른 숙소를 알아보시는 게 좋겠어요.   

                                                  target  
14390  Even so, where would this handsomeness go anyw...  
3196          I want the education system to be changed.  
19736        We will send it to you as soon as possible.  
13028             I have to go to Busan for examination.  
19945  I am very sorry, but you should look for a dif...  
data.target length : 
 30000
data.target type : 
 <class 'pandas.core.series.Series'>
data.target shape : 
 (30000,)
data.target sample : 
 24227    It has been a long time since I played the gui...
28474         They sell Saewookkang for seagulls on board.
2633                    I

In [43]:
data.target_input = data.target.apply(lambda x : '\t' + x + '\n')
data.target_target = data.target.apply(lambda x : x + "\n")
print("\ndata.target_input : \n", data.target_input)
print("\ndata.target_target : \n", data.target_target)

print("data.target_input length : \n", len(data.target_input))
print("data.target_input type : \n", type(data.target_input))
print("data.target_input shape : \n", data.target_input.shape)
print("data.target_input sample : \n", data.target_input.sample(5))


data.target_input : 
 0         \tI go to the attic every evening to meet Bat.\n
1          \tSir, I don't understand this sentence here.\n
2        \tTime flies when you start using the computer.\n
3           \tI'm going back to Korea today at midnight.\n
4               \tI go to bathroom as soon as I wake up.\n
                               ...                        
29995    \tPlease cancel your order after you're logged...
29996    \tPlease check if the attached photo is the co...
29997      \tPlease check the attached transfer receipt.\n
29998    \tPlease check the meeting's details, and cont...
29999    \tPlease check the sticker attached to the pro...
Name: target, Length: 30000, dtype: object

data.target_target : 
 0           I go to the attic every evening to meet Bat.\n
1            Sir, I don't understand this sentence here.\n
2          Time flies when you start using the computer.\n
3             I'm going back to Korea today at midnight.\n
4                 I go to

<ipython-input-43-953c8a28e506>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.target_input = data.target.apply(lambda x : '\t' + x + '\n')
<ipython-input-43-953c8a28e506>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.target_target = data.target.apply(lambda x : x + "\n")


In [44]:
# source 문장의 최대 길이
max_src_len = data.source.apply(lambda x : len(x)).max()
print("source sentence max length : ", max_src_len)

# target_input 문장의 최대 길이
max_tar_len = data.target_input.apply(lambda x : len(x)).max() - 2 # "\t"와 "\n"의 길이는 제외
print("target sentence max length : ", max_tar_len)

source sentence max length :  47
target sentence max length :  62


In [45]:
# source 언어 Tokenizing

from keras.preprocessing.text import Tokenizer

tokenizer_source = Tokenizer(num_words=None, char_level=True, lower = False) # 음절 기반, 문장부호를 제거하진 않음
tokenizer_source.fit_on_texts(data.source)
word_index_source = tokenizer_source.word_index

print("전체에서 %s개의 고유한 토큰을 찾았습니다." % len(word_index_source))
print("word_index_source : ", word_index_source)

전체에서 1411개의 고유한 토큰을 찾았습니다.
word_index_source :  {' ': 1, '.': 2, '요': 3, '이': 4, '어': 5, '는': 6, '에': 7, '해': 8, '을': 9, '가': 10, '하': 11, '고': 12, '지': 13, '나': 14, '아': 15, '있': 16, '은': 17, '서': 18, '그': 19, '를': 20, '한': 21, '리': 22, '의': 23, '다': 24, '로': 25, '기': 26, '도': 27, '사': 28, '게': 29, '일': 30, '시': 31, '수': 32, '들': 33, '면': 34, '것': 35, '?': 36, '신': 37, '야': 38, '내': 39, '주': 40, '으': 41, '만': 42, '인': 43, '보': 44, '제': 45, '거': 46, '자': 47, '당': 48, '우': 49, '라': 50, '겠': 51, '같': 52, '려': 53, '드': 54, '대': 55, '생': 56, '할': 57, '여': 58, '부': 59, '마': 60, '되': 61, '래': 62, '정': 63, '오': 64, '스': 65, '구': 66, '너': 67, '니': 68, '국': 69, '바': 70, '좋': 71, '과': 72, '까': 73, ',': 74, '와': 75, '전': 76, '않': 77, '장': 78, '각': 79, '문': 80, '음': 81, '말': 82, '안': 83, '저': 84, '무': 85, '금': 86, '없': 87, '러': 88, '싶': 89, '상': 90, '적': 91, '데': 92, '모': 93, '많': 94, '간': 95, '행': 96, '었': 97, '화': 98, '예': 99, '용': 100, '영': 101, '중': 102, '비': 103, '진': 104, '번': 105, '소': 106,

In [46]:
# target 언어 Tokenizing
tokenizer_target = Tokenizer(num_words=None, char_level=True, lower = False) # 음절 기반, 문장부호를 제거하진 않음
tokenizer_target.fit_on_texts(data.target_input)
word_index_target = tokenizer_target.word_index

print("전체에서 %s개의 고유한 토큰을 찾았습니다." % len(word_index_target))
print("word_index_target : ", word_index_target)

전체에서 76개의 고유한 토큰을 찾았습니다.
word_index_target :  {' ': 1, 'e': 2, 't': 3, 'o': 4, 'a': 5, 'n': 6, 'i': 7, 's': 8, 'r': 9, 'h': 10, 'l': 11, 'u': 12, 'd': 13, 'y': 14, 'm': 15, '\t': 16, '\n': 17, 'c': 18, '.': 19, 'w': 20, 'g': 21, 'f': 22, 'p': 23, 'I': 24, 'b': 25, 'k': 26, 'v': 27, "'": 28, ',': 29, 'T': 30, '?': 31, 'W': 32, 'x': 33, 'S': 34, 'A': 35, 'Y': 36, 'H': 37, 'j': 38, 'K': 39, 'P': 40, 'M': 41, 'C': 42, 'B': 43, 'q': 44, 'E': 45, 'D': 46, 'F': 47, 'z': 48, 'O': 49, 'N': 50, 'J': 51, 'L': 52, 'G': 53, '!': 54, 'R': 55, 'U': 56, 'V': 57, '’': 58, '"': 59, '`': 60, ';': 61, 'Z': 62, 'Q': 63, '&': 64, '~': 65, 'X': 66, '*': 67, '‘': 68, ':': 69, '´': 70, '[': 71, ']': 72, '…': 73, '“': 74, '\\': 75, '+': 76}


In [47]:
encoder_input = tokenizer_source.texts_to_sequences(data.source)

print("Result of encoder_input sequencing : ")
print(data.source[0], encoder_input[0])
print(data.source[1], encoder_input[1])
print(data.source[2], encoder_input[2])
print(data.source[3], encoder_input[3])

Result of encoder_input sequencing : 
나는 매일 저녁 배트를 만나러 다락방으로 가요. [14, 6, 1, 145, 30, 1, 84, 316, 1, 177, 113, 20, 1, 42, 14, 88, 1, 24, 210, 140, 41, 25, 1, 10, 3, 2]
선생님 이문장이 이해가 안 가요. [135, 56, 225, 1, 4, 80, 78, 4, 1, 4, 8, 10, 1, 83, 1, 10, 3, 2]
컴퓨터를 시작하면 시간이 너무 빠르게 가요. [489, 471, 142, 20, 1, 31, 190, 11, 34, 1, 31, 95, 4, 1, 67, 85, 1, 287, 139, 29, 1, 10, 3, 2]
나는 오늘 자정에 한국으로 돌아 가요. [14, 6, 1, 64, 128, 1, 47, 63, 7, 1, 21, 69, 41, 25, 1, 289, 15, 1, 10, 3, 2]


In [48]:
decoder_input = tokenizer_target.texts_to_sequences(data.target_input)
decoder_target = tokenizer_target.texts_to_sequences(data.target_target)

print('Result of decoder_input sequencing : ')
print(data.target_input[0], decoder_input[0])
print(data.target_input[1], decoder_input[1])
print(data.target_input[2], decoder_input[2])

print('Result of decoder_target sequencing : ')
print(data.target_target[0], decoder_target[0])
print(data.target_target[1], decoder_target[1])
print(data.target_target[2], decoder_target[2])

print('Result of decoder_target sequencing : ')
print(data.target_target[0], decoder_target[0])
print(data.target_target[1], decoder_target[1])
print(data.target_target[2], decoder_target[2])

Result of decoder_input sequencing : 
	I go to the attic every evening to meet Bat.
 [16, 24, 1, 21, 4, 1, 3, 4, 1, 3, 10, 2, 1, 5, 3, 3, 7, 18, 1, 2, 27, 2, 9, 14, 1, 2, 27, 2, 6, 7, 6, 21, 1, 3, 4, 1, 15, 2, 2, 3, 1, 43, 5, 3, 19, 17]
	Sir, I don't understand this sentence here.
 [16, 34, 7, 9, 29, 1, 24, 1, 13, 4, 6, 28, 3, 1, 12, 6, 13, 2, 9, 8, 3, 5, 6, 13, 1, 3, 10, 7, 8, 1, 8, 2, 6, 3, 2, 6, 18, 2, 1, 10, 2, 9, 2, 19, 17]
	Time flies when you start using the computer.
 [16, 30, 7, 15, 2, 1, 22, 11, 7, 2, 8, 1, 20, 10, 2, 6, 1, 14, 4, 12, 1, 8, 3, 5, 9, 3, 1, 12, 8, 7, 6, 21, 1, 3, 10, 2, 1, 18, 4, 15, 23, 12, 3, 2, 9, 19, 17]
Result of decoder_target sequencing : 
I go to the attic every evening to meet Bat.
 [24, 1, 21, 4, 1, 3, 4, 1, 3, 10, 2, 1, 5, 3, 3, 7, 18, 1, 2, 27, 2, 9, 14, 1, 2, 27, 2, 6, 7, 6, 21, 1, 3, 4, 1, 15, 2, 2, 3, 1, 43, 5, 3, 19, 17]
Sir, I don't understand this sentence here.
 [34, 7, 9, 29, 1, 24, 1, 13, 4, 6, 28, 3, 1, 12, 6, 13, 2, 9, 8, 3, 5, 6, 13, 1, 

In [49]:
from keras_preprocessing.sequence import pad_sequences

encoder_input = pad_sequences(encoder_input, maxlen = max_src_len, padding = "post")
decoder_input = pad_sequences(decoder_input, maxlen = max_tar_len, padding = "post")
decoder_target = pad_sequences(decoder_target, maxlen = max_tar_len, padding = "post")

print("Padding result sample : ")
print(data.target_input[0], decoder_input[0])

print("decoder_input length : ", len(decoder_input))
print("decoder_input type : ", type(decoder_input))
print("decoder_input shape : ", decoder_input.shape)

Padding result sample : 
	I go to the attic every evening to meet Bat.
 [16 24  1 21  4  1  3  4  1  3 10  2  1  5  3  3  7 18  1  2 27  2  9 14
  1  2 27  2  6  7  6 21  1  3  4  1 15  2  2  3  1 43  5  3 19 17  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
decoder_input length :  30000
decoder_input type :  <class 'numpy.ndarray'>
decoder_input shape :  (30000, 62)


In [50]:
from tensorflow.keras.utils import to_categorical

encoder_input = to_categorical(encoder_input, num_classes = len(word_index_source) + 1)
decoder_input = to_categorical(decoder_input, num_classes = len(word_index_target) + 1)
decoder_target = to_categorical(decoder_target, num_classes = len(word_index_target) + 1)

print("Result of One-Hot Encodded decoder_input sequencing : ")
print(decoder_input.shape)
print(data.target_input[0], decoder_input[0])

Result of One-Hot Encodded decoder_input sequencing : 
(30000, 62, 77)
	I go to the attic every evening to meet Bat.
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [51]:
print("0-0\n", decoder_input[0][0])
print("0-1\n", decoder_input[0][1])
print("0-2\n", decoder_input[0][2])
print("0-3\n", decoder_input[0][3])
print("0-18\n", decoder_input[0][18])

0-0
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]
0-1
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]
0-2
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]
0-3
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]
0-18
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.

In [52]:
print("decoder_input length : ", len(decoder_input))
print("decoder_input type : ", type(decoder_input))
print("decoder_input shape : ", decoder_input.shape)

decoder_input length :  30000
decoder_input type :  <class 'numpy.ndarray'>
decoder_input shape :  (30000, 62, 77)


In [53]:
from keras.models import Model
from keras.layers import Input,LSTM, Dense

encoder_inputs = Input(shape = (None, len(word_index_source) + 1))
encoder_lstm = LSTM(256, return_state=True)
_, state_h, state_c = encoder_lstm(encoder_inputs)
encoder_states = [state_h, state_c]

In [54]:
decoder_inputs = Input(shape=(None, len(word_index_target) + 1))
decoder_lstm = LSTM(256, return_sequences = True, return_state = True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state=encoder_states)
decoder_dense = Dense(len(word_index_target) + 1, activation = "softmax")
decoder_outputs = decoder_dense(decoder_outputs)

In [56]:
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
model.compile(optimizer = "rmsprop", loss = "categorical_crossentropy")
model.fit(x=[encoder_input, decoder_input], y = decoder_target, batch_size = 64, epochs = 2, validation_split = 0.2) # epochs 많으면 터진다.

Epoch 1/2
375/375 [==============================] - 446s 1s/step - loss: 2.0202 - val_loss: 1.7552
Epoch 2/2
375/375 [==============================] - 418s 1s/step - loss: 1.6115 - val_loss: 1.5589


In [57]:
encoder_model = Model(inputs = encoder_inputs, outputs = encoder_states)

In [58]:
decoder_state_input_h = Input(shape = (256,)) # Encoder vector를 받기 위함
decoder_state_input_c = Input(shape = (256,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = decoder_lstm(decoder_inputs, initial_state = decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)

decoder_model = Model(inputs = [decoder_inputs] + decoder_states_inputs, outputs = [decoder_outputs] + decoder_states) # input으론 target_input과 현재의 문장상태, output으론 예측 결과와 은닉상태와 셀상태가 나오게 한다.

In [59]:
index_to_src = dict((i, char) for char, i in word_index_source.items())
index_to_tar = dict((i, char) for char, i in word_index_target.items())
print(index_to_tar)

{1: ' ', 2: 'e', 3: 't', 4: 'o', 5: 'a', 6: 'n', 7: 'i', 8: 's', 9: 'r', 10: 'h', 11: 'l', 12: 'u', 13: 'd', 14: 'y', 15: 'm', 16: '\t', 17: '\n', 18: 'c', 19: '.', 20: 'w', 21: 'g', 22: 'f', 23: 'p', 24: 'I', 25: 'b', 26: 'k', 27: 'v', 28: "'", 29: ',', 30: 'T', 31: '?', 32: 'W', 33: 'x', 34: 'S', 35: 'A', 36: 'Y', 37: 'H', 38: 'j', 39: 'K', 40: 'P', 41: 'M', 42: 'C', 43: 'B', 44: 'q', 45: 'E', 46: 'D', 47: 'F', 48: 'z', 49: 'O', 50: 'N', 51: 'J', 52: 'L', 53: 'G', 54: '!', 55: 'R', 56: 'U', 57: 'V', 58: '’', 59: '"', 60: '`', 61: ';', 62: 'Z', 63: 'Q', 64: '&', 65: '~', 66: 'X', 67: '*', 68: '‘', 69: ':', 70: '´', 71: '[', 72: ']', 73: '…', 74: '“', 75: '\\', 76: '+'}


In [60]:
def decode_sequence(input_seq):
  states_value = encoder_model.predict(input_seq) # 초기 문장상태벡터를 얻음
  target_seq = np.zeros((1, 1, len(word_index_target) + 1)) # 디코더 초기화
  target_seq[0, 0, word_index_target["\t"]] = 1. # 디코더의 첫 시작은 "\t"이므로 원-핫 인코딩으로 기록
  stop_condition = False
  decoded_sentence = ""

  while not stop_condition:
    output_tokens, h, c = decoder_model.predict([target_seq] + states_value) # target_input과 문장상태벡터 입력
    sampled_token_index = np.argmax(output_tokens)

    if (sampled_token_index == 0):
      sampled_token_index = 1 # 1은 공백 음절

    sampled_char = index_to_tar[sampled_token_index]
    decoded_sentence += sampled_char

    if (sampled_char == "\n" or len(decoded_sentence) > max_tar_len):
      stop_condition = True
    
    target_seq = np.zeros((1, 1, len(word_index_target) + 1))
    target_seq[0, 0, sampled_token_index] = 1.
    states_value = [h, c]

  return decoded_sentence

In [61]:
import numpy as np

for seq_index in [1, 2, 3]:
  input_seq = encoder_input[seq_index:seq_index+1] # 3차원 배열에선 [n:n+1] 형태로 출력해야 3차원이 유지되면서 n번째가 출력된다.
  decoded_sentence = decode_sequence(input_seq)

  print(35 * "-")
  print("입력 문장 : ", data.source[seq_index])
  print("정답 문장 : ", data.target[seq_index][:len(data.target[seq_index])])
  print("번역기가 번역한 문장 : ", decoded_sentence[:len(decoded_sentence) - 1]) # "\n"은 빼고 출력

1/1 [==============================] - 0s 24ms/step
-----------------------------------
입력 문장 :  선생님 이문장이 이해가 안 가요.
정답 문장 :  Sir, I don't understand this sentence here.
번역기가 번역한 문장 :  I want to ke with the will be the seating the  and and the  am
1/1 [==============================] - 0s 38ms/step
-----------------------------------
입력 문장 :  컴퓨터를 시작하면 시간이 너무 빠르게 가요.
정답 문장 :  Time flies when you start using the computer.
번역기가 번역한 문장 :  I want to ke with the will be the seating the  and and the sse
1/1 [==============================] - 0s 22ms/step


1/1 [==============================] - 0s 38ms/step
-----------------------------------
입력 문장 :  나는 오늘 자정에 한국으로 돌아 가요.
정답 문장 :  I'm going back to Korea today at midnight.
번역기가 번역한 문장 :  I want to ke with the will be the seating the  and and the sse


# BERT

## 환경 설정 & 하이퍼 파라미터 설정 & 함수 정의

In [64]:
import os
import re
import numpy as np
from tqdm import tqdm
import tensorflow as tf
from transformers import *
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import pandas as pd
import matplotlib.pyplot as plt

In [65]:
def plot_graphs(history, string):
  plt.plot(history.history[string])
  plt.plot(history.history["val_" + string], "")
  plt.xlabel("Epochs")
  plt.ylabel(string)
  plt.legend([string, "val_"+string])
  plt.show()

In [66]:
tf.random.set_seed(1111)
np.random.seed(1111)

In [67]:
CLASS_NUMBER = 2
BATCH_SIZE = 32
NUM_EPOCHS = 2
VALID_SPLIT = 0.2
MAX_LEN = 40
BERT_CKPT = "C:\\Users\\Windows\\Desktop\\대학교\\4학년 여름방학\\Big_AI\\자연어처리\\pytest\\data\\KOR\\naver_movie\\bert_ckpt\\"
DATA_IN_PATH = "C:\\Users\\Windows\\Desktop\\대학교\\4학년 여름방학\\Big_AI\\자연어처리\\pytest\\data\\KOR\\naver_movie\\data_in\\"
DATA_OUT_PATH = "C:\\Users\\Windows\\Desktop\\대학교\\4학년 여름방학\\Big_AI\\자연어처리\\pytest\\data\\KOR\\naver_movie\\data_out\\"

In [68]:
def listToString(listdata):
  result = "id\tdocument\tlabel\n"
  for data_each in listdata:
    if data_each:
      result += data_each[0] + "\t" + data_each[1] + "\t" + data_each[2] + "\n"
  return result

def read_data(filename, encoding="cp949", start = 0):
  with open(filename, "r", encoding=encoding) as f:
    data = [line.split("\t") for line in f.read().splitlines()]
    data = data[start:]
  return data

def write_data(data, filename, encoding="cp949"):
  with open(filename, "w", encoding=encoding) as f:
    f.write(data)

data_ratings = read_data(os.path.join(DATA_IN_PATH, "ratings_utf8_small.txt"), encoding="utf-8", start = 1)

## 훈련데이터와 테스트데이터 분리

In [69]:
from sklearn.model_selection import train_test_split

ratings_train, ratings_test = train_test_split(data_ratings)

ratings_train = listToString(ratings_train)
ratings_test = listToString(ratings_test)

write_data(ratings_train, os.path.join(DATA_IN_PATH, "ratings_train.txt"), encoding="utf-8")
write_data(ratings_test, os.path.join(DATA_IN_PATH, "ratings_test.txt"), encoding="utf-8")

## BERT 토크나이저

In [70]:
tokenizer = BertTokenizer.from_pretrained("bert-base-multilingual-cased", cache_dir=os.path.join(BERT_CKPT, "tokenizer"), do_lower_case = False)

https://huggingface.co/bert-base-multilingual-cased/resolve/main/vocab.txt not found in cache or force_download set to True, downloading to C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\tmpwygiwhgy


storing https://huggingface.co/bert-base-multilingual-cased/resolve/main/vocab.txt in cache at C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\eff018e45de5364a8368df1f2df3461d506e2a111e9dd50af1fae061cd460ead.6c5b6600e968f4b5e08c86d8891ea99e51537fc2bf251435fb46922e8f7a7b29
creating metadata file for C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\eff018e45de5364a8368df1f2df3461d506e2a111e9dd50af1fae061cd460ead.6c5b6600e968f4b5e08c86d8891ea99e51537fc2bf251435fb46922e8f7a7b29


https://huggingface.co/bert-base-multilingual-cased/resolve/main/tokenizer_config.json not found in cache or force_download set to True, downloading to C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\tmp5kawznl1


storing https://huggingface.co/bert-base-multilingual-cased/resolve/main/tokenizer_config.json in cache at C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\f55e7a2ad4f8d0fff2733b3f79777e1e99247f2e4583703e92ce74453af8c235.ec5c189f89475aac7d8cbd243960a0655cfadc3d0474da8ff2ed0bf1699c2a5f
creating metadata file for C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\f55e7a2ad4f8d0fff2733b3f79777e1e99247f2e4583703e92ce74453af8c235.ec5c189f89475aac7d8cbd243960a0655cfadc3d0474da8ff2ed0bf1699c2a5f
loading file https://huggingface.co/bert-base-multilingual-cased/resolve/main/vocab.txt from cache at C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\eff018e45de5364a8368df1f2df3461d506e2a111e9dd50af1fae061cd460ead.6c5b6600e968f4b5e08c86d8891ea99e51537fc2bf251435fb46922e8f7a7b29
loading file https://huggingface.co/bert-base-multilingual-cased/resolve/main

https://huggingface.co/bert-base-multilingual-cased/resolve/main/config.json not found in cache or force_download set to True, downloading to C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\tmpcq9rji9k


storing https://huggingface.co/bert-base-multilingual-cased/resolve/main/config.json in cache at C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\6c4a5d81a58c9791cdf76a09bce1b5abfb9cf958aebada51200f4515403e5d08.0fe59f3f4f1335dadeb4bce8b8146199d9083512b50d07323c1c319f96df450c
creating metadata file for C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\6c4a5d81a58c9791cdf76a09bce1b5abfb9cf958aebada51200f4515403e5d08.0fe59f3f4f1335dadeb4bce8b8146199d9083512b50d07323c1c319f96df450c
loading configuration file https://huggingface.co/bert-base-multilingual-cased/resolve/main/config.json from cache at C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\tokenizer\6c4a5d81a58c9791cdf76a09bce1b5abfb9cf958aebada51200f4515403e5d08.0fe59f3f4f1335dadeb4bce8b8146199d9083512b50d07323c1c319f96df450c
Model config BertConfig {
  "_name_or_path": "bert-base-multilingual-ca

In [71]:
test_sentence = "안녕하세요, 반갑습니다."

encode = tokenizer.encode(test_sentence)
token_point = [tokenizer.decode(token) for token in encode]

print(encode)
print(token_point)

[101, 9521, 118741, 35506, 24982, 48549, 117, 9321, 118610, 119081, 48345, 119, 102]
['[ C L S ]', '안', '# # 녕', '# # 하', '# # 세', '# # 요', ',', '반', '# # 갑', '# # 습', '# # 니 다', '.', '[ S E P ]']


In [72]:
kor_encode = tokenizer.encode("안녕하세요, 반갑습니다.")
eng_encode = tokenizer.encode("Hello world")
kor_decode = tokenizer.decode(kor_encode)
eng_decode = tokenizer.decode(eng_encode)

print(kor_encode)
print(eng_encode)
print(kor_decode)
print(eng_decode)

[101, 9521, 118741, 35506, 24982, 48549, 117, 9321, 118610, 119081, 48345, 119, 102]
[101, 31178, 11356, 102]
[CLS] 안녕하세요, 반갑습니다. [SEP]
[CLS] Hello world [SEP]


## 데이터 확인

In [73]:
DATA_TRAIN_PATH = os.path.join(DATA_IN_PATH, "ratings_train.txt")
DATA_TEST_PATH = os.path.join(DATA_IN_PATH, "ratings_test.txt")

train_data = pd.read_csv(DATA_TRAIN_PATH, header = 0, delimiter = "\t", quoting = 3)
train_data = train_data.dropna()
train_data.head()

id                                           document  label
0   7743368  박흥식영화 사랑해 말순씨 ***보면 장애우를 배려하지않는 저질 영화장애우가 성희롱이...      0
1  10067386                        안개 자욱한 밤하늘에 떠 있는 초승달 같은 영화.      1
2   4254270                    성형부작용 같은 주인공 얼굴 때문에 집중이 안됨..;;;      0
3    530171                                       맥티어난의 최고 졸작품      0
4   9462634                                어린 외계인역 하신분 귀엽네요..ㅎ      1

## 스페셜 토큰 확인

In [74]:
print(tokenizer.all_special_tokens, "\n", tokenizer.all_special_ids)

kor_encode = tokenizer.encode("안녕하세요, 반갑습니다.")
eng_encode = tokenizer.encode("Hello world")

kor_decode = tokenizer.decode(kor_encode)
eng_decode = tokenizer.decode(eng_encode)

print(kor_encode)
print(eng_encode)
print(kor_decode)
print(eng_decode)

['[UNK]', '[SEP]', '[PAD]', '[CLS]', '[MASK]'] 
 [100, 102, 0, 101, 103]
[101, 9521, 118741, 35506, 24982, 48549, 117, 9321, 118610, 119081, 48345, 119, 102]
[101, 31178, 11356, 102]
[CLS] 안녕하세요, 반갑습니다. [SEP]
[CLS] Hello world [SEP]


## 사용자 정의 BERT 토크나이저 함수

In [75]:
def bert_tokenizer(sent, MAX_LEN):
  encoded_dict = tokenizer.encode_plus(
      text = sent,
      add_special_tokens = True,
      max_length = MAX_LEN,
      pad_to_max_length = True,
      return_attention_mask = True
  )

  input_id = encoded_dict["input_ids"]
  attention_mask = encoded_dict["attention_mask"]
  token_type_id = encoded_dict["token_type_ids"]

  return input_id, attention_mask, token_type_id

## 훈련데이터 변환

In [76]:
input_ids = []
attention_masks = []
token_type_ids = []
train_data_labels = []

for train_sent, train_label in tqdm(zip(train_data["document"], train_data["label"]), total = len(train_data)):
  input_id, attention_mask, token_type_id = bert_tokenizer(train_sent, MAX_LEN)

  input_ids.append(input_id)
  attention_masks.append(attention_mask)
  token_type_ids.append(token_type_id)
  train_data_labels.append(train_label)

train_movie_input_ids = np.array(input_ids, dtype = int)
train_movie_attention_masks = np.array(attention_masks, dtype = int)
train_movie_type_ids = np.array(token_type_ids, dtype = int)
train_movie_inputs = (train_movie_input_ids, train_movie_attention_masks, train_movie_type_ids)

train_data_labels = np.asarray(train_data_labels, dtype = np.int32)

  0%|          | 0/375 [00:00<?, ?it/s]Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_utils_base.py:2301: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
100%|██████████| 375/375 [00:00<00:00, 1656.40it/s]


In [77]:
input_id = train_movie_input_ids[1]
attention_mask = train_movie_attention_masks[1]
token_type_id = train_movie_type_ids[1]

print(input_id)
print(attention_mask)
print(token_type_id)
print(tokenizer.decode(input_id))

[   101   9521  21789   9651 119168  11102   9326  35506 118762  10530
   9138  13767   9757  48210  89851  18589  42428    119    102      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
[CLS] 안개 자욱한 밤하늘에 떠 있는 초승달 같은 영화. [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]


## BERT 사전학습모델을 이용한 분류기 정의 & 실행

In [78]:
class TFBertClassifier(tf.keras.Model):
  def __init__(self, model_name, dir_path, num_class):
    super(TFBertClassifier, self).__init__()

    self.bert = TFBertModel.from_pretrained(model_name, cache_dir = dir_path)
    self.dropout = tf.keras.layers.Dropout(self.bert.config.hidden_dropout_prob)
    self.classifier = tf.keras.layers.Dense(num_class, name = "classifier")
  
  def call(self, inputs, attention_mask=None, token_type_ids=None, training=False):
    outputs = self.bert(inputs, attention_mask=attention_mask, token_type_ids=token_type_ids)
    pooled_output = outputs[1]
    pooled_output = self.dropout(pooled_output, training = training)
    logits = self.classifier(pooled_output)

    return logits

In [79]:
cls_model = TFBertClassifier(model_name="bert-base-multilingual-cased", dir_path = os.path.join(BERT_CKPT, "model"), num_class=CLASS_NUMBER)

https://huggingface.co/bert-base-multilingual-cased/resolve/main/config.json not found in cache or force_download set to True, downloading to C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\model\tmphvf83e19


storing https://huggingface.co/bert-base-multilingual-cased/resolve/main/config.json in cache at C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\model\6c4a5d81a58c9791cdf76a09bce1b5abfb9cf958aebada51200f4515403e5d08.0fe59f3f4f1335dadeb4bce8b8146199d9083512b50d07323c1c319f96df450c
creating metadata file for C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\model\6c4a5d81a58c9791cdf76a09bce1b5abfb9cf958aebada51200f4515403e5d08.0fe59f3f4f1335dadeb4bce8b8146199d9083512b50d07323c1c319f96df450c
loading configuration file https://huggingface.co/bert-base-multilingual-cased/resolve/main/config.json from cache at C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\model\6c4a5d81a58c9791cdf76a09bce1b5abfb9cf958aebada51200f4515403e5d08.0fe59f3f4f1335dadeb4bce8b8146199d9083512b50d07323c1c319f96df450c
Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attent

https://huggingface.co/bert-base-multilingual-cased/resolve/main/tf_model.h5 not found in cache or force_download set to True, downloading to C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\model\tmpltwl4kfj


storing https://huggingface.co/bert-base-multilingual-cased/resolve/main/tf_model.h5 in cache at C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\model\879ba3c37de5c396bee982a9383f64cf08c9cc966d66742254a3904e6719357f.53d9b251a2a9d5d86139b64555b5e8deb0a20fc53f8a5ee958ddbb4506125a0b.h5
creating metadata file for C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\model\879ba3c37de5c396bee982a9383f64cf08c9cc966d66742254a3904e6719357f.53d9b251a2a9d5d86139b64555b5e8deb0a20fc53f8a5ee958ddbb4506125a0b.h5
loading weights file https://huggingface.co/bert-base-multilingual-cased/resolve/main/tf_model.h5 from cache at C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\bert_ckpt\model\879ba3c37de5c396bee982a9383f64cf08c9cc966d66742254a3904e6719357f.53d9b251a2a9d5d86139b64555b5e8deb0a20fc53f8a5ee958ddbb4506125a0b.h5


Some layers from the model checkpoint at bert-base-multilingual-cased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-multilingual-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


## 모델 컴파일 & 학습

In [80]:
optimizer = tf.keras.optimizers.Adam(3e-5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metric = tf.keras.metrics.SparseCategoricalAccuracy("accuracy")
cls_model.compile(optimizer=optimizer, loss = loss, metrics=[metric])

In [81]:
model_name = "tf2_bert_naver_movie"
earlystop_callback = EarlyStopping(monitor="val_accuracy", min_delta=0.0001, patience=2)

checkpoint_path = os.path.join(DATA_OUT_PATH, model_name, "weights.h5")
checkpoint_dir = os.path.dirname(checkpoint_path)

if os.path.exists(checkpoint_dir):
  print("{} -- Folder already exists \n".format(checkpoint_dir))
else:
  os.makedirs(checkpoint_dir, exist_ok = True)
  print("{} -- Folder create complete \n".format(checkpoint_dir))

cp_callback = ModelCheckpoint(checkpoint_path, monitor = "val_accuracy", verbose = 1, save_best_only = True, save_weights_only = True)

C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\data_out\tf2_bert_naver_movie -- Folder create complete 



In [82]:
history = cls_model.fit(train_movie_inputs, train_data_labels, epochs = NUM_EPOCHS, batch_size = BATCH_SIZE, validation_split = VALID_SPLIT, callbacks = [earlystop_callback, cp_callback]) # epoch 늘리면 터짐
print(history.history)

Epoch 1/2
10/10 [==============================] - ETA: 0s - loss: 0.7148 - accuracy: 0.4833 
Epoch 1: val_accuracy improved from -inf to 0.53333, saving model to C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\data_out\tf2_bert_naver_movie\weights.h5
10/10 [==============================] - 237s 21s/step - loss: 0.7148 - accuracy: 0.4833 - val_loss: 0.6826 - val_accuracy: 0.5333
Epoch 2/2
10/10 [==============================] - ETA: 0s - loss: 0.6636 - accuracy: 0.6367 
Epoch 2: val_accuracy improved from 0.53333 to 0.65333, saving model to C:\Users\Windows\Desktop\대학교\4학년 여름방학\Big_AI\자연어처리\pytest\data\KOR\naver_movie\data_out\tf2_bert_naver_movie\weights.h5
10/10 [==============================] - 223s 22s/step - loss: 0.6636 - accuracy: 0.6367 - val_loss: 0.6459 - val_accuracy: 0.6533
{'loss': [0.7147948145866394, 0.6635547876358032], 'accuracy': [0.4833333194255829, 0.6366666555404663], 'val_loss': [0.6825587153434753, 0.6459322571754456], 'val_accur

## 테스트 데이터 확인 & 변환 & 평가

In [83]:
test_data = pd.read_csv(DATA_TEST_PATH, header = 0, delimiter = "\t", quoting = 3)
test_data = test_data.dropna()
test_data.head()

id                                           document  label
0  9904263  그 반지의 제왕을 만든 피터 잭슨 ㅋㅋ 이런 영화을 찍었다는거 부터가 웃겼다. ㅋㅋ...      1
1   307000                                             삐질삐질;;      0
2  8620641                           내가 없어질 내인생. 제목을 참 잘 지었다.      1
3  7553915                                                  굿      0
4  9339372                중3인데 일단 2까지봣다. 뭐 말할것도없다장국영 자살이 안타깝다      1

In [84]:
input_ids = []
attention_masks = []
token_type_ids = []
test_data_labels = []

for test_sent, test_label in tqdm(zip(test_data["document"], test_data["label"])):
  input_id, attention_mask, token_type_id = bert_tokenizer(test_sent, MAX_LEN)

  input_ids.append(input_id)
  attention_masks.append(attention_mask)
  token_type_ids.append(token_type_id)
  test_data_labels.append(test_label)

test_movie_input_ids = np.array(input_ids, dtype = int)
test_movie_attention_masks = np.array(attention_masks, dtype = int)
test_movie_type_ids = np.array(token_type_ids, dtype = int)
test_movie_inputs = (test_movie_input_ids, test_movie_attention_masks, test_movie_type_ids)

test_data_labels = np.asarray(test_data_labels, dtype = np.int32)

0it [00:00, ?it/s]C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_utils_base.py:2301: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
125it [00:00, 864.37it/s]


In [85]:
results = cls_model.evaluate(test_movie_inputs, test_data_labels, batch_size = BATCH_SIZE)
print("test loss, test acc : ", results)

4/4 [==============================] - 16s 4s/step - loss: 0.6757 - accuracy: 0.5840
test loss, test acc :  [0.6757106184959412, 0.5839999914169312]
